### PR TITLE
Renaming macros according to coding style

### PR DESCRIPTION
**Pull request by szledan**
Issue: [https://github.com/GepardGraphics/gepard/issues/68](GepardGraphics/gepard/issues/68)

### CODE REVIEW

**Comment by kkristof** [comment]
LGTM

**Comment by kkristof** [comment]
Hmm, the travis is failing and if I try to build the examples I get the same build error.

**Comment by kkristof** [comment]
@szledan this modification solved the problem https://gist.github.com/kkristof/7c5674a6381722d498b69bda7bb6a9b2

**Comment by szledan** [comment]
Yes I found it. Thanks.

**Comment by kkristof** [comment]
LGTM again :)

**Comment by szledan** [comment]
Hi @elecro , @dbatyai. Could you check it please?

**Comment by szledan** [comment]
@kkristof , I added a missing renaming to this branch. Could you check this new commit please?

**Comment by kkristof** [comment]
@szledan it is great.

**Comment by elecro** [comment]
lgtm

**Pull request merged**
